### PR TITLE
updated links and name of PET to PI

### PR DESCRIPTION
**Pull request by aimeejulia**

### CODE REVIEW

**Comment by aimeejulia** [comment]
@onlyaweb I have made a few changes and thought we could test out some process for updating the website through pull requests which are peer-reviewed and peer approved (ie changes are checked by one or more team members and not approved by the person putting in the changes)

**Comment by onlyaweb** [comment]
@aimeejulia 
Sure . Actually each one of us ( the only around for now ) have the capabilities of updating on the fly. 
We can connect git to slack to "approve" requests, and maintain the same procedures like we have in CoLab.
What do we you think ?

**Comment by aimeejulia** [comment]
@onlyaweb my thought was to merge each other's pull requests, updates would be submitted as pull requests and then someone other than the person doing that would approve it - this way we have good oversight of the changes 
slack integration sounds interesting we could test that one and see what it would look like

**Comment by aimeejulia** [comment]
to be clear this pull request is not finalised until you or Ewan have reviewed it and clicked merge pull request

**Review by onlyaweb — APPROVED** [review]

**Pull request merged**
